In [74]:
# Trying to use PCA

import pickle
import pandas as pd
import numpy as np
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler

dataset = 'twitter'
model = 'BERTopic'

train = pickle.load(open(dataset + '/' + model + '/run_1/train.pkl', 'rb'))
test = pickle.load(open(dataset + '/' + model + '/run_1/test.pkl', 'rb'))
temp = pd.concat([train, test]).reset_index(drop=True) # concatenating train and test datasets
df = pd.read_csv(dataset + '.csv') # loading in actual dataset

for run in range(1, 2):

    test_distribution = pickle.load(open(dataset + '/' + model + '/run_' + str(run) + '/' + model + '_topic_distribution_test.pkl', 'rb'))
    train_distribution = pickle.load(open(dataset + '/' + model + '/run_' + str(run) + '/' + model + '_topic_distribution_train.pkl', 'rb'))
    distribution = np.concatenate([train_distribution, test_distribution]) # concatenating train and test distributions

    merged = pd.merge(temp, df, how='inner', left_on = 'message_id', right_on = 'Unnamed: 0')[['message_id_x', 'message_x', 'user_id']]
    distribution_df = pd.concat([pd.DataFrame(distribution), merged[['user_id']]], axis = 1)

    # mean
    user_distributions = distribution_df.groupby('user_id').mean().reset_index(drop=True)
    user_distributions_arr = [row[1].values for row in user_distributions.iterrows()]

    # PCA then mean
    scaler = StandardScaler()
    standardized_data = scaler.fit_transform(distribution_df.drop('user_id', axis=1))
    
    # Apply PCA
    pca = PCA(n_components=2)  # Reduce to 2 components for demonstration
    reduced_data = pca.fit_transform(standardized_data)

    # Create a DataFrame for the reduced data
    reduced_df = pd.DataFrame(reduced_data, columns=['PC1', 'PC2'])
    reduced_df['user_id'] = merged['user_id']

    # Aggregate these PCA components by user
    pca_user_distributions = reduced_df.groupby('user_id').mean().reset_index(drop=True)
    pca_user_distributions_arr = [row[1].values for row in pca_user_distributions.iterrows()]

    # with open(dataset + "/" + model + "/run_" + str(run) + "/" + model + '_avg_topic_distribution.pkl', 'wb') as f:
    #     pickle.dump(user_distributions_arr, f)
    
    print("Done " + str(run))

Done 1


In [75]:
pca_user_distributions_arr

[array([0.34864896, 0.02372117]),
 array([ 0.10405052, -1.06145831]),
 array([0.69519316, 0.17166788]),
 array([ 0.86919649, -0.70065917]),
 array([-7.4756114 , -0.62825428]),
 array([-1.17234777,  0.21524715]),
 array([-3.05413841,  0.41204303]),
 array([-1.59197755,  0.65626547]),
 array([-0.18415217,  0.39125095]),
 array([4.91110085, 0.83088799]),
 array([ 0.97897629, -0.12760204]),
 array([0.16510556, 1.79188122]),
 array([-3.13997691,  2.07658324]),
 array([ 1.15426581, -0.98920692]),
 array([-2.33982824,  1.64008549]),
 array([-0.19697958, -2.10954586]),
 array([-11.97528289,   1.86457573]),
 array([0.90906254, 0.98609925]),
 array([ 0.64297583, -0.68397648]),
 array([-1.58398531, -0.43703279]),
 array([-12.74540306,   1.75143403]),
 array([0.53736809, 1.35511472]),
 array([ 2.33664447, -0.22842395]),
 array([-0.72796885,  0.15893673]),
 array([-2.15406398, -1.03286662]),
 array([1.47419296, 1.24892067]),
 array([-0.53820319, -0.12785187]),
 array([-8.01545328,  1.78844024]),
 a

In [73]:
user_distributions_arr

[array([0.00247   , 0.00276396, 0.00230781, 0.00242412, 0.00250488,
        0.00230393, 0.00260903, 0.00258522, 0.0022972 , 0.00255268,
        0.00110991, 0.00253913, 0.00249547, 0.00248213, 0.00258469,
        0.00242042, 0.00249978, 0.00281234, 0.00249103, 0.00242419,
        0.00276978, 0.00254756, 0.00244082, 0.00245755, 0.00238014,
        0.00240186, 0.00261214, 0.002426  , 0.00262769, 0.00244329,
        0.0023407 , 0.00251363, 0.00231841, 0.00240122, 0.00241237,
        0.00258205, 0.00251725, 0.00252739, 0.00255183, 0.00244646,
        0.00243827, 0.00211211, 0.00216124, 0.00246719, 0.00241766,
        0.00246988, 0.0025171 , 0.00230588, 0.00121271, 0.00246374,
        0.00256561, 0.00244947, 0.        , 0.00254644, 0.00213614,
        0.0022276 , 0.0023704 , 0.00228219, 0.00220019, 0.00246585,
        0.00239439, 0.00167963, 0.00207926, 0.00210433, 0.00171319,
        0.00209836, 0.00235371, 0.00239238, 0.00235501, 0.00321507,
        0.00231713, 0.00270008, 0.00178414, 0.00

In [1]:
# Creating avg_topic_distributions

import pickle
import pandas as pd
import numpy as np

dataset = 'facebook'
model = 'Mallet_LDA'

train = pickle.load(open(dataset + '/' + model + '/run_1/train.pkl', 'rb'))
test = pickle.load(open(dataset + '/' + model + '/run_1/test.pkl', 'rb'))
temp = pd.concat([train, test]).reset_index(drop=True) # concatenating train and test datasets
df = pd.read_csv(dataset + '.csv') # loading in actual dataset

for run in range(1, 6):

    test_distribution = pickle.load(open(dataset + '/' + model + '/run_' + str(run) + '/' + model + '_topic_distribution_test.pkl', 'rb'))
    train_distribution = pickle.load(open(dataset + '/' + model + '/run_' + str(run) + '/' + model + '_topic_distribution_train.pkl', 'rb'))
    distribution = np.concatenate([train_distribution, test_distribution]) # concatenating train and test distributions

    merged = pd.merge(temp, df, how='inner', left_on = 'message_id', right_on = 'Unnamed: 0')[['message_id_x', 'message_x', 'user_id']]

    distribution_df = pd.concat([pd.DataFrame(distribution), merged[['user_id']]], axis = 1)
    user_distributions = distribution_df.groupby('user_id').mean().reset_index(drop=True)
    user_distributions_arr = [row[1].values for row in user_distributions.iterrows()]

    with open(dataset + "/" + model + "/run_" + str(run) + "/" + model + '_avg_topic_distribution.pkl', 'wb') as f:
        pickle.dump(user_distributions_arr, f)
    
    # print(user_distributions_arr)

    print("Done " + str(run))

Done 1


FileNotFoundError: [Errno 2] No such file or directory: 'facebook/Mallet_LDA/run_2/Mallet_LDA_topic_distribution_test.pkl'

In [8]:
import pandas as pd
pd.read_csv('twitter.csv')

Unnamed: 0       user_id    message_id  \
0                0  2.118258e+07  1.594783e+17   
1                1  2.115601e+07  5.144728e+17   
2                2  1.974366e+07  5.929812e+17   
3                3  1.538815e+07  5.474148e+17   
4                4  8.107369e+08  6.601730e+17   
...            ...           ...           ...   
999995      999995  1.557305e+09  5.247189e+17   
999996      999996  5.213977e+08  3.423205e+17   
999997      999997  2.093107e+08  7.069024e+17   
999998      999998  3.693546e+07  6.145565e+17   
999999      999999  3.107187e+07  5.355447e+17   

                                                  message  gender   age  \
0       "I was never a big Pens fan until someone offe...     2.0  27.0   
1       <USER> how they view those who haven't done an...     2.0  20.0   
2       RT <USER>: That awkward moment when you bump i...     2.0  23.0   
3       RT <USER>: .<USER>'s Ready Player One is $2.50...     1.0  36.0   
4       Monsters Cereal, Only $1.00 at Target! via Cou...     2.0  53.0   
...                                                   ...     ...   ...   
999995  RT <USER>: ICYMI: <USER> partnership gets the ...     1.0  45.0   
999996           <USER> smith family meltdown in aisle 2.     2.0  25.0   
999997  <USER> When I was very young my grandma would ...     1.0  40.0   
999998  RT <USER>: <USER> Thank you for taking the tim...     1.0  41.0   
999999  <USER> <USER> \nI need a translator for some o...     2.0  38.0   

        politics  
0            4.0  
1            5.0  
2            1.0  
3            7.0  
4            6.0  
...          ...  
999995       4.0  
999996       7.0  
999997       5.0  
999998       2.0  
999999       5.0  

[1000000 rows x 7 columns]

In [1]:
import pandas as pd
import pickle
import csv
import numpy as np
from sklearn.linear_model import LinearRegression
import sklearn

# change this
dataset = 'twitter' # folder and dataset name
model = "BERTopic" # model name
# cols = ['gender', 'age', 'politics'] # outcome columns
cols = ['age'] # outcome columns
run = 1
outcome = 'age'

print("Run: " + str(run))
print()

# loading in distributions that were saved during topic extraction
train = pickle.load(open(dataset + '/' + model + '/run_' + str(run) + '/train.pkl', 'rb'))
test = pickle.load(open(dataset + '/' + model + '/run_' + str(run) + '/test.pkl', 'rb'))

topics = []
with open(dataset + '/' + model + '/run_' + str(run) + '/' + 'topics_100.txt', 'r') as f:
    reader = csv.reader(f)
    for row in reader:
        topic_list = [item.strip() for item in row if item.strip()]
        topics.append(topic_list)

temp = pd.concat([train, test]).reset_index(drop=True) # concatenating train and test datasets
df = pd.read_csv(dataset + '.csv') # loading in actual dataset

merged = pd.merge(temp, df, how='inner', left_on = 'message_id', right_on = 'Unnamed: 0')[['message_id_x', 'user_id', 'message_x'] + cols]
merged.columns = ['message_id', 'user_id', 'message'] + cols

user_ids = {user_id : user_data.index.tolist() for user_id, user_data in merged.groupby('user_id')} # gets all users and their corresponding indices in the df
all_user_ids = list(user_ids.keys())

labels_data = merged[['user_id'] + cols] # df of user_ids and all the labels to consider
user_ids_avg_dict = {} # populated to be user_id : average distribution
y = [] # the outcome we care about

for key in user_ids.keys():
    y.append(labels_data[labels_data['user_id'] == key][outcome].iloc[0])

X = pickle.load(open(dataset + '/' + model + '/run_' + str(run) + '/' + model + '_avg_topic_distribution.pkl', 'rb'))

with open('test.pkl', 'wb') as f:
    pickle.dump(X, f)

# # 80-20 split --> didn't use train-test-split function since its already shuffled
X_train = X[:round(0.80 * len(X))]
X_test = X[round(0.80 * len(X)):]

y_train = y[:round(0.80 * len(X))]
y_test = y[round(0.80 * len(X)):]

train_users = all_user_ids[:round(0.80 * len(X))]
test_users = all_user_ids[round(0.80 * len(X)):]

lr_model = LinearRegression().fit(X_train, y_train) # trains logit model over each label column from dummy df
pred = lr_model.predict(X_test)
score = sklearn.metrics.accuracy_score(np.round(pred), y_test)
print(outcome)
print(score)

Run: 1

age
0.032716927453769556


In [ ]:
import pandas as pd
import pickle
import csv
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import r2_score

# change this
dataset = 'twitter' # folder and dataset name
model = "CTM" # model name
cols = ['gender', 'age', 'politics'] # outcome columns

for run in range(1, 6):
    print("Run: " + str(run))
    print()

    # loading in distributions that were saved during topic extraction
    test_distribution = pickle.load(open(dataset + '/' + model + '/run_' + str(run) + '/' + model + '_topic_distribution_test.pkl', 'rb'))
    train_distribution = pickle.load(open(dataset + '/' + model + '/run_' + str(run) + '/' + model + '_topic_distribution_train.pkl', 'rb'))
    train = pickle.load(open(dataset + '/' + model + '/run_' + str(run) + '/train.pkl', 'rb'))
    test = pickle.load(open(dataset + '/' + model + '/run_' + str(run) + '/test.pkl', 'rb'))

    topics = []
    with open(dataset + '/' + model + '/run_' + str(run) + '/' + 'topics_100.txt', 'r') as f:
        reader = csv.reader(f)
        for row in reader:
            topic_list = [item.strip() for item in row if item.strip()]
            topics.append(topic_list)

    distribution = np.concatenate([train_distribution, test_distribution]) # concatenating train and test distributions
    temp = pd.concat([train, test]).reset_index(drop=True) # concatenating train and test datasets
    df = pd.read_csv(dataset + '.csv') # loading in actual dataset

    df['politics'] = round(df['politics']) # for twitter

    merged = pd.merge(temp, df, how='inner', left_on = 'message_id', right_on = 'Unnamed: 0')[['message_id_x', 'user_id', 'message_x'] + cols]
    merged.columns = ['message_id', 'user_id', 'message'] + cols

    user_ids = {user_id : user_data.index.tolist() for user_id, user_data in merged.groupby('user_id')} # gets all users and their corresponding indices in the df
    all_user_ids = list(user_ids.keys())

    for outcome in cols:

        labels_data = merged[['user_id'] + cols] # df of user_ids and all the labels to consider
        user_ids_avg_dict = {} # populated to be user_id : average distribution
        user_ids_avg = [] # populated to be all the average distributions ^ same as the values from there
        y = [] # the outcome we care about

        for key, value in user_ids.items():
            arrays = [distribution[i] for i in value]
            avg = np.mean(arrays, axis = 0)
            user_ids_avg_dict[key] = avg
            user_ids_avg.append(avg)
            y.append(labels_data[labels_data['user_id'] == key][outcome].iloc[0])

        X = user_ids_avg

        # 80-20 split --> didn't use train-test-split function since its already shuffled
        X_train = X[:round(0.80 * len(X))]
        X_test = X[round(0.80 * len(X)):]

        # bucketing twitter ages -- did it by 10 but we can make this so that each bucket has the same number of users if we'd like
        if outcome == "age":
            n = []
            for i in y:
                if i < 10:
                    n.append("age_0to10")
                elif i < 20:
                    n.append("age_10to20")
                elif i < 30:
                    n.append("age_20to30")
                elif i < 40:
                    n.append("age_30to40")
                elif i < 50:
                    n.append("age_40to50")
                elif i < 60:
                    n.append("age_50to60")
                elif i < 70:
                    n.append("age_60to70")
                elif i < 80:
                    n.append("age_70to80")
                elif i < 90:
                    n.append("age_80to90")
                else:
                    n.append("age_90to100")
            y = n

        y_train = y[:round(0.80 * len(X))]
        y_test = y[round(0.80 * len(X)):]

        train_users = all_user_ids[:round(0.80 * len(X))]
        test_users = all_user_ids[round(0.80 * len(X)):]

        # converts all outcomes into dummy variables
        dummy_train = pd.get_dummies(y_train, dtype=int)
        dummy_test = pd.get_dummies(y_test, dtype=int)
        dummy_train.columns = ["label " + str(i) for i in range(len(dummy_train.columns))]
        dummy_test.columns = ["label " + str(i) for i in range(len(dummy_test.columns))]

        accuracies = []
        r2s = []
        for i, label_col in enumerate(list(dummy_train)):
            lr_model = LogisticRegression().fit(X_train, dummy_train[label_col]) # trains logit model over each label column from dummy df
            accuracies.append(lr_model.score(X_test, dummy_test[label_col])) # gets scores on test set
            r2s.append(r2_score(dummy_test[label_col], lr_model.predict(X_test))) # gets r2 score from test set

        accuracies = [np.mean(accuracies)] + accuracies + [np.mean(r2s)] # appends to list for final_df below
        final_df = pd.concat([pd.Series(accuracies)], axis = 1).T
        final_df.columns = ['Average Accuracy'] + [i + str(" Accuracy") for i in dummy_train.columns] + ['R2']
        print(outcome)
        display(final_df)
        print()
        print()